[build]
  # No build command needed for static site
  command = ""
  
  # Publish directory - frontend files only
  publish = "../frontend"

[build.environment]
  # Disable Python detection
  PYTHON_VERSION = ""

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
