services:
  - type: web
    name: temple-donation-manager
    env: node
    plan: starter
    buildCommand: |
      npm install
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_EXECUTABLE
        value: python3
